name = "skifree-yeti-do"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "MOUNTAIN_DO"
class_name = "MountainDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MountainDO"]
